name: Registry Service CI/CD

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'registry/**'
      - '.github/workflows/registry-cicd.yml'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'registry/**'

env:
  SERVICE_NAME: registry
  DOCKER_IMAGE: eeshunarayan15/registry-service

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Gradle
        run: |
          cd ${{ env.SERVICE_NAME }}
          chmod +x gradlew
          ./gradlew build

      - name: Test with Gradle
        run: |
          cd ${{ env.SERVICE_NAME }}
          ./gradlew test

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./${{ env.SERVICE_NAME }}
          push: true
          tags: |
            ${{ env.DOCKER_IMAGE }}:latest
            ${{ env.DOCKER_IMAGE }}:main-${{ github.sha }}
          cache-from: type=registry,ref=${{ env.DOCKER_IMAGE }}:latest
          cache-to: type=inline

  deploy:
    needs: build-and-push
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Render Deployment
        run: |
          curl -X POST \
            https://api.render.com/v1/services/${{ secrets.RENDER_REGISTRY_SERVICE_ID }}/deploys \
            -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
            -H "Content-Type: application/json"

      - name: Wait for deployment to complete
        run: |
          echo "Waiting for registry service to be healthy..."
          for i in {1..30}; do
            if curl -f ${{ secrets.RENDER_REGISTRY_URL }}/actuator/health >/dev/null 2>&1; then
              echo "Service is healthy!"
              break
            fi
            echo "Attempt $i: Service not ready yet. Waiting 10 seconds..."
            sleep 10
          done

      - name: Health Check
        run: |
          curl -f ${{ secrets.RENDER_REGISTRY_URL }}/actuator/health